services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.2.1
    links:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test:
        [
          "CMD",
          "/opt/bitnami/kafka/bin/kafka-topics.sh",
          "--list",
          "--bootstrap-server=kafka:9092"
        ]
      interval: 30s
      timeout: 10s
      retries: 4
  spark-elastic:
    image: spark-example:dev
    ports:
      - 4040:4040
    environment:
      EXAMPLE_GOAL: "consumer.sparkelastic"
      EXAMPLE_KAFKA_SERVER: "kafka:9092"
      EXAMPLE_ZOOKEEPER_SERVER: "zookeeper:2181"
